### ISSUE TITLE
[metricsfetcher] MetricsFetcher doesn't build with go 1.9

### ISSUE THREAD

**Issue by tmichelet** [DataDog/kafka-kit#133]
Seeing following errors:
```
# github.com/DataDog/topicmappr/kafkazk
kafkazk/brokers.go:130:4: undefined: rand.Shuffle
kafkazk/brokers.go:135:4: undefined: rand.Shuffle
kafkazk/partitions.go:368:3: undefined: rand.Shuffle
```
Upgrading to go 1.10.1 fixes the issue. Should we update the readmes? [autothrottle](https://github.com/DataDog/topicmappr/tree/master/cmd/autothrottle#installation) and [metricsfetcher](https://github.com/DataDog/topicmappr/tree/master/cmd/metricsfetcher#installation)
